Your task is to choose and return a category for the programming/computer science term requested by the user inquiry after <<<>>>.

You must select one of the provided categories listed below:
####
  Concept
  Paradigm
  Data Structures & Algorithms
  Dev & Engineering
  Databases
  Systems & Networking
  Languages & Frameworks
  Security
  AI & Data Science
  Tooling & Infrastructure
####

Decide on the best match of category. You will respond with only one category in string format.
Do not provide explanations or notes.

<<<
Inquiry: {term}
>>>