CREATE TABLE account (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username VARCHAR(255) UNIQUE NOT NULL,
                        email VARCHAR(255) UNIQUE NOT NULL,
                        password VARCHAR(255) NOT NULL,
                        role VARCHAR(255) DEFAULT 'editor',
                        date_added TIMESTAMP DEFAULT NOW(),
                        date_updated TIMESTAMP DEFAULT NOW()
);

CREATE TABLE term (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(255) UNIQUE NOT NULL,
                      category VARCHAR(255) NOT NULL,
                      date_updated TIMESTAMP DEFAULT NOW()
);

CREATE TABLE term_version (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              term_id BIGINT NOT NULL,
                              user_id BIGINT,
                              short_def TEXT NOT NULL,
                              long_def TEXT NOT NULL,
                              code_snippet TEXT,
                              example_usage TEXT NOT NULL,
                              approved BOOLEAN DEFAULT FALSE,
                              approved_by BIGINT,
                              date_added TIMESTAMP DEFAULT NOW(),
                              CONSTRAINT fk_term_version_term FOREIGN KEY (term_id) REFERENCES term(id) ON DELETE CASCADE,
                              CONSTRAINT fk_term_version_user FOREIGN KEY (user_id) REFERENCES account(id) ON DELETE SET NULL,
                              CONSTRAINT fk_term_version_approved FOREIGN KEY (approved_by) REFERENCES account(id) ON DELETE SET NULL
);


CREATE TABLE vote (
                         user_id BIGINT NOT NULL,
                         version_id BIGINT NOT NULL,
                         vote_value SMALLINT CHECK (vote_value IN (-1, 1, 0)),
                         PRIMARY KEY (user_id, version_id),
                         CONSTRAINT fk_votes_user FOREIGN KEY (user_id) REFERENCES account(id) ON DELETE CASCADE,
                         CONSTRAINT fk_votes_version FOREIGN KEY (version_id) REFERENCES term_version(id) ON DELETE CASCADE
);

CREATE TABLE collection (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              user_id BIGINT NOT NULL,
                              name VARCHAR(255) NOT NULL,
                              description TEXT,
                              date_added TIMESTAMP DEFAULT NOW(),
                              date_updated TIMESTAMP DEFAULT NOW(),
                              CONSTRAINT fk_collection_user FOREIGN KEY (user_id) REFERENCES account(id) ON DELETE CASCADE
);

CREATE TABLE contains (
                            collection_id BIGINT NOT NULL,
                            term_id BIGINT NOT NULL,
                            date_added TIMESTAMP DEFAULT NOW(),
                            PRIMARY KEY (collection_id, term_id),
                            CONSTRAINT fk_contains_collection FOREIGN KEY (collection_id) REFERENCES collection(id) ON DELETE CASCADE,
                            CONSTRAINT fk_contains_term FOREIGN KEY (term_id) REFERENCES term(id) ON DELETE CASCADE
);