CREATE SEQUENCE account_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE term_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE term_version_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE term_collection_id_seq START WITH 1 INCREMENT BY 1;