CREATE TABLE User (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username VARCHAR(255) UNIQUE NOT NULL,
                        email VARCHAR(255) UNIQUE NOT NULL,
                        password TEXT NOT NULL,
                        role VARCHAR(255) DEFAULT 'editor',
                        dateAdded TIMESTAMP DEFAULT NOW(),
                        dateUpdated TIMESTAMP DEFAULT NOW()
);

CREATE TABLE Votes (
                         userId BIGINT NOT NULL,
                         versionId BIGINT NOT NULL,
                         voteValue SMALLINT CHECK (voteValue IN (-1, 1)),
                         PRIMARY KEY (userId, versionId),
                         CONSTRAINT fk_votes_user FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
                         CONSTRAINT fk_votes_version FOREIGN KEY (versionId) REFERENCES TermVersion(id) ON DELETE CASCADE
);

CREATE TABLE Term (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) UNIQUE NOT NULL,
                        category varchar(255) NOT NULL,
                        dateUpdated TIMESTAMP DEFAULT NOW(),
                        currentVersionId BIGINT REFERENCES TermVersion(id) ON DELETE SET NULL
);

CREATE TABLE TermVersion (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               termId BIGINT NOT NULL,
                               userId BIGINT,
                               shortDef TEXT NOT NULL,
                               longDef TEXT NOT NULL,
                               codeSnippet TEXT,
                               exampleUsage TEXT NOT NULL,
                               approved BOOLEAN DEFAULT FALSE,
                               approvedBy BIGINT,
                               dateAdded TIMESTAMP DEFAULT NOW(),
                               CONSTRAINT fk_term_version_term FOREIGN KEY (termId) REFERENCES Term(id) ON DELETE CASCADE,
                               CONSTRAINT fk_term_version_user FOREIGN KEY (userId) REFERENCES User(id) ON DELETE SET NULL,
                               CONSTRAINT fk_term_version_approved FOREIGN KEY (approvedBy) REFERENCES User(id) ON DELETE SET NULL
);

CREATE TABLE Collection (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              userId BIGINT NOT NULL,
                              name VARCHAR(255) NOT NULL,
                              description TEXT,
                              dateAdded TIMESTAMP DEFAULT NOW(),
                              dateUpdated TIMESTAMP DEFAULT NOW(),
                              CONSTRAINT fk_collection_user FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE Contains (
                            collectionId BIGINT NOT NULL,
                            termId BIGINT NOT NULL,
                            dateAdded TIMESTAMP DEFAULT NOW(),
                            PRIMARY KEY (collectionId, termId),
                            CONSTRAINT fk_contains_collection FOREIGN KEY (collectionId) REFERENCES Collection(id) ON DELETE CASCADE,
                            CONSTRAINT fk_contains_term FOREIGN KEY (termId) REFERENCES Term(id) ON DELETE CASCADE
);